# west build -b openrz67_nrf -- -DEXTRA_CONF_FILE=debug.conf
CONFIG_LOG=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
